[package]
name = "gdext-class"
version = "0.1.0"
edition = "2021"
rust-version = "1.63"

[features]
trace = []

[dependencies]
gdext-sys = { path = "../gdext-sys" }
gdext-builtin = { path = "../gdext-builtin" }
once_cell = "1.8"
