[package]
name = "godot-codegen"
version = "0.1.0"
edition = "2021"
rust-version = "1.63"
license = "MPL-2.0"
keywords = ["gamedev", "godot", "engine", "codegen"]
categories = ["game-engines", "graphics"]

[features]
default = []
codegen-fmt = []
codegen-full = []
double-precision = []
custom-godot = ["godot-input/custom-godot"]

[dependencies]
godot-input = { path = "../godot-input" }
heck = "0.4"
nanoserde = "0.1.29"
proc-macro2 = "1"
quote = "1"
