[package]
name = "godot"
version = "0.1.0"
edition = "2021"
rust-version = "1.63"

[features]
trace = []
convenience = []
default = ["convenience"]

[dependencies]
godot-core = { path = "../godot-core" }
godot-macros = { path = "../godot-macros" }

