[package]
name = "godot-core"
version = "0.1.0"
edition = "2021"
rust-version = "1.63"

[features]
trace = []
convenience = []
default = ["convenience"]

[dependencies]
godot-ffi = { path = "../godot-ffi" }
once_cell = "1.8"
glam = "0.17"
