[package]
name = "itest"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[features]
default = []
trace = ["gdext-class/trace"]

[dependencies]
gdext-sys = { path = "../../gdext-sys" }
gdext-macros = { path = "../../gdext-macros" }
gdext-builtin = { path = "../../gdext-builtin" }
gdext-class = { path = "../../gdext-class" }
