[package]
name = "itest"
version = "0.1.0"
edition = "2021"
rust-version = "1.63"

[lib]
crate-type = ["cdylib"]

[features]
default = []
trace = ["godot/trace"]

[dependencies]
#godot-ffi = { path = "../../godot-ffi" }
#godot-macros = { path = "../../godot-macros" }
#godot-core = { path = "../../godot-core" }
godot = { path = "../../godot" }

[build-dependencies]
quote = "1"
proc-macro2 = "1"
