[package]
name = "godot-ffi"
version = "0.1.0"
edition = "2021"
rust-version = "1.63"
license = "MPL-2.0"
keywords = ["gamedev", "godot", "engine", "ffi"]
categories = ["game-engines", "graphics"]

[features]
custom-godot = ["dep:godot-input"]
codegen-fmt = ["godot-codegen/codegen-fmt"]
#codegen-full = ["godot-codegen/codegen-full"]

[dependencies]
paste = "1"

[build-dependencies]
godot-input = { optional = true, path = "../godot-input" }
godot-codegen = { path = "../godot-codegen" }
