[package]
name = "godot-ffi"
version = "0.1.0"
edition = "2021"
rust-version = "1.70"
license = "MPL-2.0"
keywords = ["gamedev", "godot", "engine", "ffi"]
categories = ["game-engines", "graphics"]

[features]
custom-godot = []
trace = []

[dependencies]

[build-dependencies]