# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

header:
  license:
    spdx-id: MPL-2.0

  paths:
    - '**/*.rs'
    - '**/*.gd'
    - '.github/**/*.yml'

  comment: on-failure

  language:
    GDScript:
      extensions: ['.gd']
      comment_style_id: 'Hashtag'
    Rust:
      extensions: ['.rs']
      comment_style_id: 'SlashAsterisk'
