# Minimal CI workflow
# Run when someone opens a PR and adds commits to the PR (this is recognized as a push to master)
# Includes basic checks and unit/integration checks on Linux only

name: Minimal CI

#env:

on:
  push:
#  pull_request:
#    branches:
#      - master

defaults:
  run:
    shell: bash

# If a new commit is pushed before the old one's CI has completed (on the same branch), abort previous run
#concurrency:
#  group: ${{ github.head_ref }}
#  cancel-in-progress: true

jobs:
  integration-test-godot:
    name: itest-godot
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v2

      - name: "Install LLVM"
        uses: ./.github/composite/llvm
        #if: ${{ matrix.os.id == 'windows-latest' }}

      - name: "Run Godot integration test"
        uses: ./.github/composite/godot
        with:
          artifact_name: godot-linux
          github_pat: ${{ secrets.ARTIFACT_DOWNLOADER_PAT }}
          #godot_ver: ${{ matrix.godot }}

  license-guard:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2

      - name: "Check and fix license headers"
        uses: apache/skywalking-eyes/header@v0.4.0
        with:
          # log: debug # optional: set the log level. The default value is `info`.
          config: .github/external-config/licenserc.yml
          # token: # optional: the token that license eye uses when it needs to comment on the pull request. Set to empty ("") to disable commenting on pull request. The default value is ${{ github.token }}
          # mode: # optional: Which mode License-Eye should be run in. Choices are `check` or `fix`. The default value is `check`.
          mode: fix

      - name: "Commit changes"
        uses: EndBug/add-and-commit@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          author_name: 'Godot-Rust Automation'
          author_email: 'actions@github.com'
          message: 'Auto-apply license headers'
