# Minimal CI workflow
# Run when someone opens a PR and adds commits to the PR (this is recognized as a push to master)
# Includes basic checks and unit/integration checks on Linux only

name: Minimal CI

#env:

on:
  push:
#  pull_request:
#    branches:
#      - master

defaults:
  run:
    shell: bash

# If a new commit is pushed before the old one's CI has completed (on the same branch), abort previous run
#concurrency:
#  group: ${{ github.head_ref }}
#  cancel-in-progress: true

jobs:
  integration-test-godot:
    name: itest-godot
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: pwd
      - name: "Run Godot integration test"
        uses: ./.github/composite/godot
        with:
          artifact_name: godot-linux
          github_pat: ${{ secrets.ARTIFACT_DOWNLOADER_PAT }}
          #godot_ver: ${{ matrix.godot }}
